Description: >
    Ronny Morel / Udacity
    This template deploys a VPC, with one public and private subnets in an Availabilty Zones.
    It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a NAT Gateways, 
    and default routes for them in the private subnets.
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VpcCIDR: 
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.0.0.0/16

Resources:

    VPC: 
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags: 
                - Key: Name 
                  Value: !Ref EnvironmentName